name: Deploy Add in

on:
  push:
    branches:
      - main  # veya master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Kendi node sürümünüzü yazabilirsiniz

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # Eğer build script'iniz varsa bu satırı ekleyin

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Kendi build klasörünüzü yazın (örneğin: build, public)
